# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: Release

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 'default'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package -Dmaven.test.skip=true'
- task: Docker@2
  displayName: Docker Login
  inputs:
    containerRegistry: 'rmspkgw'
    command: 'login'
- task: Docker@2
  displayName: Docker Build and Push
  inputs:
    containerRegistry: 'rmspkgw'
    repository: 'ado-sample-app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'


