# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  name: Release
  demands: Agent.Name -equals adolin101gm-rms

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    git clone git@github.ebaykorea.com:org-ebaykorea/rms-qa.git
  displayName: 'Run a multi-line script'

