# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: deployPkgNum
  displayName: 배포 할 패캐지 번호
  type: string

trigger:
- none



pool:
  name: Default
steps:
- checkout: none
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'aks_test'
    namespace: 'azure-vote'
    manifests: 'sha256:f2eae3bf5aee4b62d0d53769364b0b112749c0ef35e537d34354cad98c20c132'
    containers: 'ado-sample-app'