# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: default

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 'default'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package -Dmaven.test.skip=true'
- task: Docker@2
  displayName: Docker Login
  inputs:
    containerRegistry: 'rmspkg-dev'
    command: 'login'
- task: Docker@2
  displayName: DockerBuild
  inputs:
    containerRegistry: 'rmspkg-dev'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    arguments: '-t rmspkgw-dev.gmarket.com'



- task: Docker@2
  inputs:
    containerRegistry: 'rmspkg-dev'
    repository: 'rmspkgw-dev.gmarket.com'
    command: 'push'
    arguments: '-t rmspkgw-dev.gmarket.com'