# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: deployPkgNum
  displayName: 배포 할 패캐지 번호
  type: string

trigger:
- none



pool:
  name: Release
  demands:
  - agent.Name -equals ADOWIN101GM


  
steps:
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'aks2'
    namespace: 'azure-vote'
    command: 'apply'
    useConfigurationFile: true
    configurationType: 'inline'
    inline: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: my-pod  # Pod의 이름
        namespace: azure-vote  # Pod를 생성할 네임스페이스
      spec:
        containers:
          - name: my-container
            image: rmspkgw.gmarket.com/rms-qa-4992-java-batch:${{ parameters.deployPkgNum }}  # 사용할 이미지
            ports:
              - containerPort: 80  # 컨테이너가 노출하는 포트 (이미지에 따라 다를 수 있음)
        restartPolicy: Always  # 컨테이너 재시작 정책
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'