# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: deployPkgNum
  displayName: 배포 할 패캐지 번호
  type: string

trigger:
- none



pool:
  name: Release
  demands:
  - agent.Name -equals adolin101gm-rms


  
steps:
- checkout: none
- script: ls
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'aks2'
    namespace: 'argo'
    command: 'get'
    arguments: 'pods'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'aks2'
    namespace: 'azure-vote'
    command: 'apply'
    useConfigurationFile: true
    configurationType: 'inline'
    inline: '-f deploy.yml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'