# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: default

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 'default'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package -Dmaven.test.skip=true'
- task: Docker@2
  inputs:
    command: 'build'
    arguments: "-t ado-sample-app:$(Build.BuildId)"
    Dockerfile: '**/Dockerfile'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      docker login -u rms -p $(DOCKER_PASSWORD) rmspkgw-dev.gmarket.com
            
      docker tag ado-sample-app:$(Build.BuildId) rmspkgw-dev.gmarket.com/ado-sample-app:$(Build.BuildId)
            
      docker push rmspkgw-dev.gmarket.com/ado-sample-app:$(Build.BuildId)

- task: Docker@2
  inputs:
    containerRegistry: 'rmspkg-dev'
    command: 'login'


